# Generated by Django 4.2.17 on 2024-12-18 17:37

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [

        migrations.RenameField('Image', 'palace', 'place'),
    ]
