# Generated by Django 4.2.17 on 2024-12-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20241218_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='geeks_field',
            field=models.PositiveIntegerField(verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
