# Generated by Django 4.2.17 on 2024-12-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_geeks_field_alter_place_lat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['geeks_field']},
        ),
        migrations.AlterField(
            model_name='image',
            name='geeks_field',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция'),
        ),
    ]
