# Generated by Django 4.2.17 on 2025-02-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(unique=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(unique=True, verbose_name='Долгота'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('place', 'position', 'image')},
        ),
    ]
